#! /bin/bash

die(){
echo $@
exit 1
}

[ "$(id -u)" != "0" ] && {
sudo $0 $@
exit $?
}

brightness_directory="/dev/null"
if [ -d /sys/class/backlight/intel_backlight ]; then
	brightness_directory="/sys/class/backlight/intel_backlight"
elif [ -d /sys/class/blacklight/acpi_video0 ]; then
	brightness_directory="/sys/class/backlight/acpi_video0"
else
	die "Can't determine backlight controller"
fi

max_brightness=$(cat $brightness_directory/max_brightness)
brightness=$(cat $brightness_directory/brightness)

echo $brightness

if [ "$1" == "down" ] && [ $brightness -gt 0 ]; then
	echo down
	let brightness=$brightness-100
elif [ "$1" == "up" ] && [ $brightness -le $max_brightness ]; then
	echo up
	let brightness=$brightness+100
else 
	[ $1 -gt 0 ] && [ $1  -le 100 ] || die "Percentage must be an integer between 0 and 100 (inclusive) or up or down."
	let brightness=$(expr 100 / $1)
	let brightness=$(expr $max_brightness / $brightness)
	echo $brightness > $brightness_directory/brightness
fi

echo $brightness > $brightness_directory/brightness